(() => {
  'use strict';
  const endpoint='https://gxhcsgjbcxgrloxbnexn.supabase.co/functions/v1/bodem-teacher-api';
  const sessionKey='bodem.phase6.teacher.session';
  const main=document.getElementById('main'),notice=document.getElementById('notice'),dialog=document.getElementById('detail'),content=document.getElementById('dialog-content');
  let token='',data=null,busy=false,filters={search:'',className:'',block:'',access:''},pending=null,issued=null;
  const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const btn=(action,label,primary=false,extra='')=>`<button type="button" data-action="${action}" ${primary?'class="primary"':''} ${extra}>${label}</button>`;
  const stamp=value=>value?new Date(value).toLocaleString('nl-NL'):'Nog geen activiteit';
  const admin=()=>data?.teacher.role==='admin';
  const setMessage=text=>{notice.hidden=!text;notice.textContent=text||'';};
  function lock(on){busy=on;main.setAttribute('aria-busy',String(on));document.querySelectorAll('button,input,select').forEach(element=>{if(on){element.dataset.locked=String(element.disabled);element.disabled=true;}else if(element.dataset.locked!==undefined){element.disabled=element.dataset.locked==='true';delete element.dataset.locked;}});}
  function forget(){token='';data=null;pending=null;issued=null;content.innerHTML='';if(dialog.open)dialog.close();try{sessionStorage.removeItem(sessionKey);}catch{}}
  async function api(body){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),20000);try{const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:JSON.stringify(body),signal:controller.signal});const result=await response.json();if(!response.ok){const error=new Error(result.error||'De aanvraag is niet gelukt.');error.status=response.status;throw error;}return result;}catch(error){if(!error.status)throw new Error('Geen bevestiging ontvangen. Controleer je verbinding en probeer opnieuw.');throw error;}finally{clearTimeout(timer);}}
  function loginView(){document.getElementById('logout').hidden=true;document.getElementById('account').textContent='';main.innerHTML='<section class="panel login"><p class="kicker">Docenten · Fase 7</p><h1>Inloggen als docent</h1><p>Bekijk de voortgang in alle 31 lessen. Gebruik je eigen docentcode.</p><form id="teacher-login"><label for="teacher-code">Persoonlijke docentcode</label><input id="teacher-code" type="password" autocomplete="current-password" required maxlength="128" spellcheck="false"><div class="actions"><button class="primary" type="submit">Open docentenoverzicht</button><button type="button" data-action="show-code">Code tonen</button></div></form><p class="muted">Uitsluitend fictieve gegevens en aliassen. Log uit op een gedeelde computer.</p></section>';}
  async function login(code){if(busy)return;code=code.trim().replace(/^[`"']+|[`"']+$/g,'').replace(/[\s\u200B-\u200D\uFEFF\-\u2010-\u2015\u2212]/g,'').toUpperCase();if(!/^[A-F0-9]{32}$/.test(code)){setMessage('De code is niet volledig. Kopieer alleen de acht groepjes van vier tekens.');return;}lock(true);setMessage('Inloggen…');try{const result=await api({action:'login',code});token=result.token;try{sessionStorage.setItem(sessionKey,token);}catch{}data=result;setMessage('');render();}catch(error){setMessage(error.message);}finally{lock(false);}}
  async function refresh(){if(busy)return;lock(true);setMessage('Resultaten ophalen…');try{data=await api({action:'overview'});setMessage('');render();}catch(error){if(error.status===401){forget();loginView();}setMessage(error.message);}finally{lock(false);}}
  async function logout(){if(busy)return;lock(true);try{await api({action:'logout'});forget();setMessage('Je bent uitgelogd.');loginView();}catch(error){if(error.status===401){forget();loginView();setMessage('Je bent uitgelogd.');}else setMessage(error.message);}finally{lock(false);}}
  const visibleLessons=student=>filters.block?student.lessons.filter(lesson=>lesson.block===filters.block):student.lessons;
  function metrics(student){const lessons=visibleLessons(student);return{total:lessons.length,done:lessons.filter(lesson=>lesson.status==='Doorlopen').length,busy:lessons.filter(lesson=>lesson.status==='Bezig').length,answered:lessons.reduce((sum,lesson)=>sum+(lesson.answered||0),0),score:lessons.reduce((sum,lesson)=>sum+(lesson.score||0),0),maximum:lessons.length*6};}
  function filtered(){return data.students.filter(student=>(!filters.search||student.name.toLocaleLowerCase('nl-NL').includes(filters.search.toLocaleLowerCase('nl-NL')))&&(!filters.className||student.className===filters.className)&&(!filters.access||(filters.access==='active'?student.active:!student.active)));}
  function results(){const rows=filtered();document.getElementById('result-count').textContent=`${rows.length} van ${data.students.length} studenten zichtbaar${filters.block?' · '+filters.block:''}`;document.getElementById('stats').innerHTML=`<div class="stat"><strong>${rows.length}</strong><span>Studenten in selectie</span></div><div class="stat"><strong>${rows.reduce((sum,student)=>sum+metrics(student).done,0)}</strong><span>Lessen doorlopen</span></div><div class="stat"><strong>${rows.reduce((sum,student)=>sum+metrics(student).busy,0)}</strong><span>Lessen bezig</span></div>`;if(!rows.length){document.getElementById('results').innerHTML='<section class="empty"><h2>Geen studenten gevonden</h2><p>Pas je zoekterm of filters aan.</p>'+btn('clear-filters','Filters wissen')+'</section>';return;}document.getElementById('results').innerHTML=`<div class="table-wrap"><table><caption>${filters.block?esc(filters.block):'Alle drie lesblokken'} · voortgang per student</caption><thead><tr><th>Student</th><th>Klas</th><th>Doorlopen</th><th>Bezig</th><th>Vragen</th><th>Eerste punten</th><th>Toegang</th><th>Bekijken</th></tr></thead><tbody>${rows.map(student=>{const m=metrics(student);return`<tr><td data-label="Student">${esc(student.name)}</td><td data-label="Klas">${esc(student.className)}</td><td data-label="Doorlopen">${m.done} / ${m.total}</td><td data-label="Bezig">${m.busy}</td><td data-label="Vragen">${m.answered} / ${m.maximum}</td><td data-label="Eerste punten">${m.answered?m.score+' / '+m.maximum:'Nog geen score'}</td><td data-label="Toegang"><span class="badge ${student.active?'':'blocked'}">${student.active?'Actief':'Geblokkeerd'}</span></td><td data-label="Bekijken">${btn('detail','Bekijk student',false,`data-id="${student.id}"`)}</td></tr>`;}).join('')}</tbody></table></div>`;}
  function render(){if(!data){loginView();return;}document.getElementById('logout').hidden=false;document.getElementById('account').textContent=data.teacher.name+' · '+(admin()?'Beherende docent':'Docent — alleen bekijken');const classes=[...new Set(data.students.map(student=>student.className))].sort((a,b)=>a.localeCompare(b,'nl'));main.innerHTML=`<div class="toolbar"><div><p class="kicker">Docentenoverzicht</p><h1>Voortgang in alle bodemlessen</h1></div><div class="actions">${btn('refresh','Vernieuwen')}${admin()?btn('create','Student toevoegen',true):''}</div></div><p class="tagline">‘Doorlopen’ betekent dat de theorie is gelezen en alle zes vragen zijn beantwoord. Er is geen slaaggrens; de punten tonen uitsluitend de eerste bevestigde antwoorden.</p><p class="muted">Bijgewerkt: ${esc(stamp(data.asOf))}</p><section class="filters" aria-label="Studenten filteren"><div><label for="search">Zoek student</label><input type="search" id="search" placeholder="Naam van student" maxlength="80" value="${esc(filters.search)}"></div><div><label for="class-filter">Klas</label><select id="class-filter"><option value="">Alle klassen</option>${classes.map(value=>`<option ${value===filters.className?'selected':''} value="${esc(value)}">${esc(value)}</option>`).join('')}</select></div><div><label for="block-filter">Lesblok</label><select id="block-filter"><option value="">Alle lesblokken</option>${['LDV111','LDV112','LDV141'].map(value=>`<option ${value===filters.block?'selected':''}>${value}</option>`).join('')}</select></div><div><label for="access-filter">Toegang</label><select id="access-filter"><option value="">Alle studenten</option><option value="active" ${filters.access==='active'?'selected':''}>Actief</option><option value="blocked" ${filters.access==='blocked'?'selected':''}>Geblokkeerd</option></select></div></section><p id="result-count" class="filter-count" role="status"></p><div id="stats" class="stats"></div><div id="results"></div><p class="muted">‘Nog geen score’ betekent dat er nog geen vraag is bevestigd. Een score van 0 betekent dat er wel antwoorden zijn gegeven.</p>`;results();}
  function showDialog(html){content.innerHTML=html;if(!dialog.open)dialog.showModal();}
  function closeDialog(){if(busy)return;const uncertain=!!pending;pending=null;issued=null;content.innerHTML='';dialog.close();if(uncertain)setMessage('De wijziging kan al zijn opgeslagen. Vernieuw het overzicht.');}
  function detailView(student){const selectedLessons=filters.block?student.lessons.filter(lesson=>lesson.block===filters.block):student.lessons;const m=metrics(student);showDialog(`<h2 id="detail-title">${esc(student.name)}</h2><p>${esc(student.className)} · ${student.active?'Toegang actief':'Toegang geblokkeerd'}</p><div class="summary-bar"><span>${m.done} / ${m.total} doorlopen</span><span>${m.answered} / ${m.maximum} vragen</span><span>${m.answered?m.score+' eerste punten':'nog geen score'}</span></div><div class="lesson-detail scroll-table"><table><thead><tr><th>Les</th><th>Status</th><th>Vragen</th><th>Score</th></tr></thead><tbody>${selectedLessons.map(lesson=>`<tr><td data-label="Les"><strong>${lesson.id}</strong><small>${esc(lesson.title)}</small></td><td data-label="Status">${esc(lesson.status)}</td><td data-label="Vragen">${lesson.answered===null?'Controle nodig':lesson.answered+' / 6'}</td><td data-label="Score">${lesson.score===null?'—':lesson.score+' / 6'}</td></tr>`).join('')}</tbody></table></div>${admin()?`<h3>Student beheren</h3><div class="actions">${btn('edit','Naam of klas aanpassen',false,`data-id="${student.id}"`)}${btn('rotate','Code vervangen',false,`data-id="${student.id}"`)}${btn('access',student.active?'Toegang blokkeren':'Toegang herstellen',false,`data-id="${student.id}"`)}</div>`:'<p class="muted">Jouw account heeft alleen kijkrechten.</p>'}<div class="actions">${btn('close','Sluiten',true)}</div>`);}
  function editForm(student){pending=null;issued=null;showDialog(`<h2 id="detail-title">${student?'Naam of klas aanpassen':'Student toevoegen'}</h2><p>Gebruik uitsluitend een fictieve naam en klas.</p><form id="edit-form" class="edit-form" data-id="${student?.id||''}"><div class="field"><label for="student-name">Naam</label><input id="student-name" value="${esc(student?.name||'')}" maxlength="80" required autocomplete="off"></div><div class="field"><label for="student-class">Klas</label><input id="student-class" value="${esc(student?.className||'')}" maxlength="40" required autocomplete="off"></div><p class="muted">${student?'Alle lesvoortgang en scores blijven behouden.':'Na opslaan verschijnt een nieuwe persoonlijke studentcode. Bewaar deze voordat je sluit.'}</p><div id="dialog-message" role="status"></div><div class="actions"><button type="submit" class="primary">${student?'Wijziging opslaan':'Student aanmaken'}</button>${btn('close','Annuleren')}</div></form>`);}
  function confirm(student,operation){pending=null;issued=null;const title=operation==='rotate'?'Code vervangen':student.active?'Toegang blokkeren':'Toegang herstellen';const explain=operation==='rotate'?'De oude code en sessies vervallen. Alle lesvoortgang blijft behouden.':student.active?'De student kan niet meer inloggen. Alle lesvoortgang blijft bewaard.':'De student kan weer inloggen met de huidige code.';showDialog(`<h2 id="detail-title">${title}</h2><p><strong>${esc(student.name)}</strong> · ${esc(student.className)}</p><p>${explain}</p><div id="dialog-message" role="status"></div><div class="actions">${btn('confirm-'+operation,title,true,`data-id="${student.id}"`)}${btn('close','Annuleren')}</div>`);}
  const newCode=()=>Array.from(crypto.getRandomValues(new Uint8Array(16))).map(value=>value.toString(16).padStart(2,'0')).join('').toUpperCase();
  const command=(operation,student,values={})=>({action:'manage',requestId:crypto.randomUUID(),operation,...(student?{studentId:student.id,expected:student.manageRevision}:{}),...(['create','rotate'].includes(operation)?{newCode:newCode()}:{}),...values});
  async function mutate(cmd){if(busy)return;pending=cmd;lock(true);const note=document.getElementById('dialog-message');if(note)note.textContent='Opslaan…';try{const result=await api(cmd),code=cmd.newCode;pending=null;issued=code?code.match(/.{1,4}/g).join('-'):null;showDialog(`<h2 id="detail-title">${code?'Bewaar de persoonlijke code':'Wijziging opgeslagen'}</h2><p><strong>${esc(result.student.name)}</strong> · ${esc(result.student.className)}</p>${code?`<p>Geef deze code uitsluitend aan deze student. Je kunt de code later alleen vervangen.</p><label for="issued-code">Nieuwe studentcode</label><input class="issued" id="issued-code" readonly value="${issued}"><div id="copy-status" role="status"></div><div class="actions">${btn('copy','Code kopiëren')}${btn('close','Ik heb de code bewaard',true)}</div>`:`<p>De wijziging is opgeslagen. Alle lesvoortgang en scores zijn behouden.</p><div class="actions">${btn('close','Sluiten',true)}</div>`}`);try{data=await api({action:'overview'});render();setMessage('Wijziging opgeslagen.');}catch{setMessage('Wijziging opgeslagen. Vernieuw het overzicht om de actuele gegevens te zien.');}}catch(error){const uncertain=!error.status||error.status>=500;if(!uncertain)pending=null;showDialog(`<h2 id="detail-title">${uncertain?'Opslag nog niet bevestigd':'Wijziging niet uitgevoerd'}</h2><p class="error">${esc(error.message)}</p><div class="actions">${uncertain?btn('retry','Opnieuw proberen',true):''}${btn('close','Sluiten')}</div>`);}finally{lock(false);}}
  document.addEventListener('submit',event=>{if(event.target.id==='teacher-login'){event.preventDefault();login(document.getElementById('teacher-code').value);return;}if(event.target.id==='edit-form'){event.preventDefault();if(!admin()||busy)return;const student=data.students.find(item=>item.id===event.target.dataset.id);mutate(command(student?'edit':'create',student,{name:document.getElementById('student-name').value.trim(),className:document.getElementById('student-class').value.trim()}));}});
  document.addEventListener('input',event=>{if(event.target.id==='search'){filters.search=event.target.value;results();}});
  document.addEventListener('change',event=>{const map={'class-filter':'className','block-filter':'block','access-filter':'access'};if(map[event.target.id]){filters[map[event.target.id]]=event.target.value;results();}});
  document.addEventListener('click',async event=>{if(event.detail>1&&event.target.closest('button')){event.preventDefault();event.stopImmediatePropagation();return;}const element=event.target.closest('[data-action]');if(!element)return;event.preventDefault();if(busy)return;const action=element.dataset.action,student=data?.students.find(item=>item.id===element.dataset.id);if(action==='show-code'){const input=document.getElementById('teacher-code'),show=input.type==='password';input.type=show?'text':'password';element.textContent=show?'Code verbergen':'Code tonen';return;}if(action==='logout'){logout();return;}if(action==='refresh'){refresh();return;}if(action==='close'){closeDialog();return;}if(action==='clear-filters'){filters={search:'',className:'',block:'',access:''};render();return;}if(action==='detail'&&student){detailView(student);return;}if(!admin())return;if(action==='create'){editForm();return;}if(action==='edit'&&student){editForm(student);return;}if(['rotate','access'].includes(action)&&student){confirm(student,action);return;}if(action==='confirm-rotate'&&student){mutate(command('rotate',student));return;}if(action==='confirm-access'&&student){mutate(command('access',student,{active:!student.active}));return;}if(action==='retry'&&pending){mutate(pending);return;}if(action==='copy'&&issued){try{await navigator.clipboard.writeText(issued);document.getElementById('copy-status').textContent='Code gekopieerd.';}catch{document.getElementById('issued-code').select();document.getElementById('copy-status').textContent='De code is geselecteerd. Kopieer met Ctrl+C.';}}});
  document.addEventListener('click',async event=>{if(event.detail>1&&event.target.closest('button')){event.preventDefault();event.stopImmediatePropagation();return;}const element=event.target.closest('[data-action]');if(!element)return;event.preventDefault();if(busy)return;const action=element.dataset.action,student=data?.students.find(item=>item.id===element.dataset.id);if(action==='privacy'){document.getElementById('privacy-dialog').showModal();return;}if(action==='close-privacy'){document.getElementById('privacy-dialog').close();return;}if(action==='show-code'){const input=document.getElementById('teacher-code'),show=input.type==='password';input.type=show?'text':'password';element.textContent=show?'Code verbergen':'Code tonen';return;}if(action==='logout'){logout();return;}if(action==='refresh'){refresh();return;}if(action==='close'){closeDialog();return;}if(action==='clear-filters'){filters={search:'',className:'',block:'',access:''};render();return;}if(action==='detail'&&student){detailView(student);return;}if(!admin())return;if(action==='create'){editForm();return;}if(action==='edit'&&student){editForm(student);return;}if(['rotate','access'].includes(action)&&student){confirm(student,action);return;}if(action==='confirm-rotate'&&student){mutate(command('rotate',student));return;}if(action==='confirm-access'&&student){mutate(command('access',student,{active:!student.active}));return;}if(action==='retry'&&pending){mutate(pending);return;}if(action==='copy'&&issued){try{await navigator.clipboard.writeText(issued);document.getElementById('copy-status').textContent='Code gekopieerd.';}catch{document.getElementById('issued-code').select();document.getElementById('copy-status').textContent='De code is geselecteerd. Kopieer met Ctrl+C.';}}});
  dialog.addEventListener('cancel',event=>{event.preventDefault();if(!busy)closeDialog();});
  try{token=sessionStorage.getItem(sessionKey)||'';}catch{}
  if(token){main.innerHTML='<p>Docentenoverzicht laden…</p>';refresh();}else loginView();
})();
